/**
 * Copyright (c) Neill Alexander. All rights reserved.
 * The use and distribution terms for this software are covered by the
 * Eclipse Public License 1.0 (http://opensource.org/licenses/eclipse-1.0.php)
 * which can be found in the file epl-v10.html at the root of this distribution.
 * By using this software in any fashion, you are agreeing to be bound by
 * the terms of this license.
 * You must not remove this notice, or any other, from this software
 */
package com.nwalex.sponge.gui;

import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.JComponent;
import javax.swing.KeyStroke;

/**
 *
 * @author neill
 */
public class ConfigurationDialog extends javax.swing.JDialog {

  private final ConfigurationDialogController controller;
  private final Action okAction;

  /** Creates new form ConfigurationDialog */
  public ConfigurationDialog(java.awt.Frame parent, boolean modal, ConfigurationDialogController controller) {
    super(parent, modal);
    this.controller = controller;
    this.okAction = new SafeAction("OK Config", new OkAction(), parent);

    initComponents();

    addShortcutsToField(portField);
    addShortcutsToField(targetField);
  }

  private void addShortcutsToField(JComponent comp) {
    // add some helper keys
    comp.getActionMap().put("OK_ACTION", okAction);
    comp.getActionMap().put("CANCEL_ACTION", new AbstractAction() {

      public void actionPerformed(ActionEvent e) {
        cancelButtonActionPerformed(e);
      }
    });

    comp.getInputMap().put(KeyStroke.getKeyStroke(KeyEvent.VK_ENTER, 0),
            "OK_ACTION");

    comp.getInputMap().put(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0),
            "CANCEL_ACTION");
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    portFieldLabel = new javax.swing.JLabel();
    targetFieldLabel = new javax.swing.JLabel();
    portField = new javax.swing.JTextField();
    targetField = new javax.swing.JTextField();
    cancelButton = new javax.swing.JButton();
    okButton = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    setTitle("Sponge Server Configuration");

    portFieldLabel.setText("Port");

    targetFieldLabel.setText("Target");

    portField.setText("8139");
    portField.setText(Integer.toString(controller.getCurrentPort()));
    portField.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        portFieldActionPerformed(evt);
      }
    });

    targetField.setText("http://localhost:8141");
    targetField.setText(controller.getCurrentTarget());
    targetField.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        targetFieldActionPerformed(evt);
      }
    });

    cancelButton.setText("Cancel");
    cancelButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        cancelButtonActionPerformed(evt);
      }
    });

    okButton.setAction(okAction);
    okButton.setText("Ok");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(portFieldLabel, javax.swing.GroupLayout.Alignment.TRAILING)
              .addComponent(targetFieldLabel, javax.swing.GroupLayout.Alignment.TRAILING))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(portField, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(targetField, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE)))
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addComponent(okButton)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(cancelButton)))
        .addContainerGap())
    );

    layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cancelButton, okButton});

    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(portFieldLabel)
          .addComponent(portField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(targetFieldLabel)
          .addComponent(targetField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(cancelButton)
          .addComponent(okButton))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void portFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_portFieldActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_portFieldActionPerformed

  private void targetFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_targetFieldActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_targetFieldActionPerformed

  private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
    this.dispose();
  }//GEN-LAST:event_cancelButtonActionPerformed
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton cancelButton;
  private javax.swing.JButton okButton;
  private javax.swing.JTextField portField;
  private javax.swing.JLabel portFieldLabel;
  private javax.swing.JTextField targetField;
  private javax.swing.JLabel targetFieldLabel;
  // End of variables declaration//GEN-END:variables

  private class OkAction extends AbstractAction {
    @Override
    public void actionPerformed(ActionEvent e) {
      controller.setConfiguration(Integer.parseInt(portField.getText()), targetField.getText());
      ConfigurationDialog.this.dispose();
    }
  }
}
