/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TestGUI.java
 *
 * Created on 06-Mar-2010, 20:45:37
 */

package com.nwalex.sponge.testclient;

import net.webservicex.GlobalWeather;

/**
 *
 * @author neill
 */
public class TestGUI extends javax.swing.JFrame {

    /** Creates new form TestGUI */
    public TestGUI() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jScrollPane1 = new javax.swing.JScrollPane();
    responseArea = new javax.swing.JTextArea();
    jButton1 = new javax.swing.JButton();
    viaSpongeTextBox = new javax.swing.JCheckBox();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    responseArea.setColumns(20);
    responseArea.setRows(5);
    jScrollPane1.setViewportView(responseArea);

    jButton1.setText("Call Web Service");
    jButton1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton1ActionPerformed(evt);
      }
    });

    viaSpongeTextBox.setText("Via Sponge");
    viaSpongeTextBox.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        viaSpongeTextBoxActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
      .addGroup(layout.createSequentialGroup()
        .addGap(146, 146, 146)
        .addComponent(jButton1)
        .addGap(18, 18, 18)
        .addComponent(viaSpongeTextBox)
        .addContainerGap(42, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(18, 18, 18)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jButton1)
          .addComponent(viaSpongeTextBox))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

    private void viaSpongeTextBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viaSpongeTextBoxActionPerformed
      // TODO add your handling code here:
    }//GEN-LAST:event_viaSpongeTextBoxActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      GlobalWeather gw = new GlobalWeather();
      gw.getGlobalWeatherSoap().getCitiesByCountry("France");
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TestGUI().setVisible(true);
            }
        });
    }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton jButton1;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JTextArea responseArea;
  private javax.swing.JCheckBox viaSpongeTextBox;
  // End of variables declaration//GEN-END:variables

}
